/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testThingInstantiation() {
        Thing t = new Thing("Person");
        assertEquals("Person", t.toString());
    }

    @Test public void testCreatureInstantiation() {
	
    }
}
